### PR TITLE
Stream implementation

### PR DESCRIPTION
**Pull request by adrienbanse**
This PR is a draft for https://github.com/dataforgoodfr/12_genai_impact/issues/16

- [x] OpenAI streams
- [x] OpenAI streams & async
- [x] OpenAI tests
- [x] Anthropic streams
- [x] Anthropic streams & async
- [x] Anthropic tests
- [x] Mistral streams
- [x] Mistral streams & async
- [x] Mistral tests

### CODE REVIEW

**Comment by adrienbanse** [comment]
Concerning Anthropic, for now streams work with 

```python
from genai_impact import Tracer
from anthropic import Anthropic

Tracer.init()
client = Anthropic()

stream = client.messages.stream(
    max_tokens=1024,
    messages=[{"role": "user", "content": "Hello"}],
    model="claude-2.0",
)

print(stream.impacts)
```

But not with 

```python
from genai_impact import Tracer
from anthropic import Anthropic

Tracer.init()
client = Anthropic()

with client.messages.stream(
    max_tokens=1024,
    messages=[{"role": "user", "content": "Hello"}],
    model="claude-2.0",
) as stream:
    for text in stream.text_stream:
        print(text)
    print(stream.impacts)
```
But I have an idea on how to solve this

@samuelrince If I'm not wrong, although text is sent, Anthropic sends the `output_tokens` only at the end of the stream, so we can only compute it for the whole stream, unlike chunks with OpenAI

**Comment by LucBERTON** [comment]
I implemented stream and async stream for mistralai, please check and let me know if you think it's OK

**Comment by LucBERTON** [comment]
Regarding Anthropic, 

I tested Andrien's code but I think it's not returning any impacts value in "stream".

I think the issue is because we need to use a context manager (`with ... as stream`) and we're not just calling a function like what is done with openai or mistralai : 

```python
    with client.messages.stream(
        max_tokens=1024,
        messages=[{"role": "user", "content": "Hello"}],
        model="claude-3-haiku-20240307",
    ) as stream:
```

**Comment by adrienbanse** [comment]
Anthropic streams now work with both options in https://github.com/dataforgoodfr/12_genai_impact/pull/28#issuecomment-2038166410

Remains to make it work with 
```python
stream = client.messages.create(
    max_tokens=1024,
    messages=[
        {
            "role": "user",
            "content": "Hello, Claude",
        }
    ],
    model="claude-3-opus-20240229",
    stream=True,
)

for event in stream:
    print(event.type)
```

Here the type of `stream` is `Anthropic.Stream`

**Comment by samuelrince** [comment]
Hello on my side this does not seem to work for Anthropic. If the Tracer is initialized, the text is not printed.

```python
from genai_impact import Tracer
from anthropic import Anthropic

Tracer.init()
client = Anthropic()

with client.messages.stream(
        max_tokens=100,
        messages=[{"role": "user", "content": "Hello World!"}],
        model="claude-3-haiku-20240307",
) as stream:
    for text in stream.text_stream:
        print(text)
    print(stream.impacts)
```

**Comment by adrienbanse** [comment]
Anthropic streams now work only with 

```python
from genai_impact import Tracer
from anthropic import Anthropic

Tracer.init()
client = Anthropic()

with client.messages.stream(
    max_tokens=1024,
    messages=[{"role": "user", "content": "Hello"}],
    model="claude-2.0",
) as stream:
    for text in stream.text_stream:
        print(text)
    print(stream.impacts)
```

But I believe that the other one makes less sense

Can you test on your side @samuelrince?

**Review by samuelrince — APPROVED** [review]

**Pull request merged**
